name: IRCTC Booking

on:
  # schedule:
  # # “At minute 0 and 30 past every hour from 12 through 21.”
  # - cron: '0,30 12-21 * * *'
  push:
    branches:
      - 'feature/*'
  pull_request:
  workflow_dispatch:

jobs:
  IRCTC-Booking:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r irctc-captcha-solver/requirements.txt

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '21.7.1'

    - name: Running IRCTC Cypress Script
      uses: cypress-io/github-action@v6
      # continue-on-error: true
      with:
        command: npx cypress run --env USERNAME=${{secrets.USERNAME}},PASSWORD=${{secrets.PASSWORD}}


