name: IRCTC Booking

on:
  # schedule:
  # # “At minute 0 and 30 past every hour from 12 through 21.”
  # - cron: '0,30 12-21 * * *'
  push:
    branches:
      - 'feature/*'
  pull_request:
  workflow_dispatch:

jobs:
  IRCTC-Booking:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r irctc-captcha-solver/requirements.txt
        python3 irctc-captcha-solver/app.py "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMsAAAAyCAIAAAB9BLi1AAAJg0lEQVR42u2cC1AVVRjHbVKbNCsrjXFSU9QMNR+ZYj5T1F4oWmkqvgCDEEVQVJDw7TRWTkZmqBPZwx6OkuZb06sQqFAoCXZDbyKNmVr5iIoI6z+zzeHr3L3n7u597cUz882dubvfObt7zm+/1zn31qn72NOGpeyH81JqvbhCCKSOJEyKJEyKJEyKJEwSJkUSJkUSJgmThEnCpEjCpLhNEm5vyqaj3+ABudW5TptkX7dAk7WafXsTSZhLcvVCddYx66rufTEZwwJe6JmagvENDhmAz84JqakNGi/q3OOf3/70U8Iun78WlDiXzcjjAdFOm4yOjmT6HWbORw+SMI8b+d5DB67pdcsv5RX+CNnO79vRZ9nbrr1AeUX7rlQZ7570kt4LI8JemOb0hTanzGvanD3Fw2khlX9UqqrBh/aZN1S7f5SE6SDswRkvxdVvtPlYadWVyvIff8LxS2UX1xefxijTJxrUvJk/EgYvD7DYUwA4VbUnm03S5R99T5hfQIbY6/2TNoUqVdlU8i19ImDnj5DtfqAzfYrtp9pyCgs6PaLXP5qCsNqRWq7tX489BRICr3ltp8oAhRtk5CWOlIe3mOLIRBnzj6YjzH9RK/wzm91817QUkxDGmSXIvjYdBfo5176kGMU2asBOIcc04B/NS5gxzuCeYD8QMAWHDMBIhUfGp3cJVh0LeD2qOTEiJqNPPVcqDvCh7LbRpxkIe+2hnly2iyDSaedcqw/yv8HBZa070INa+vEPwgSDyClcvVAd2jJKtXlQ4lxbQQlrWF1xnYarVHqmpigD6uLEA1mfE5bZtzdVwy1pjw6REbOGgbEJR6oKqGEzEAP4hrBB8ckrNmzek1dgtZXbzp7D5/4jhTjSf9psLajR47//dHVMXKzgWsiSLH9blIypc0KqQBNDCX9nYNYRprBORkdH+pawSY/ezD2+tfCY9v6/qjwIg0fHxLB/9A1hfWJnHSw4LooecvODxkeLOaNHEhveqTz8ksAgxdNdKru4tbQ1nCDTQQwLRzZy8nSl7iDQfHZKhIFZX9mjP+th+SMP+5CwWbc15Ez48YNH9V5iVfe+qoOv1z/6gLDo5W9ouaeS0jMAUXu3bacnwVFyncBu0eWz1AaNNWoWHTqhawRPfVXMmneaM7Pi1ytifXht5GLQZEtPcD3avZgjwn4uu0gLp8pbZ8wk4220dwuGc2TvETZh8as1o3z23NLMj4DRrSHDcQqfw+Ys2JlT87YVWW2tRk3WYslg0mHYtfgLaGZft6hqRtat0Vzbv56WgYP9g/dBQ+ZTYDCK8wrFS5xD7w5w9FAwtAgTnVop1bPnz/7ORaIg+K/LVYYtJR6EC1INL1d4ibB246Lwkv6X25881S0izl6n/sDQNzduZXf27rY9WmIy2sQ+Z6StBFUcqgkIDAwWbGTVlUoxXm1eTBKPUqvYOZhIvYQhEuXSF5hqFxfjufVHyDFLvqkJe+fz3eySAg8IY2bJr4nSHAVk9AGeSprvaDIw9BrDCKopKGip3gw8HeIwxfwIhNYzYfaQ7sH0wh9B4Msy+tRTbGHaPXfpIgzgKvElk/DIePtIQG/iQsMGRfB6GFva9wZh8Hc11mLnPu3OdPaqdU4JCwgb6+gULVNBBBBQTQyugcECH/CYjlwJLX52mztY1R7gIE45LdbQszBUMFf0CIwZ3hYXkwlaX6USFVzHpITFvJLOrjcyZZFYucWz45nyhl37dVUuxFmnxoEAKxrjMDCBzJFWQAJjE1R9JY5rKazbV+HFE4Zgi34dclcAAjIX8eLqq7Q8ZiAN8hJhGVnb2fUQkGmvsp4otRkmTO8igeHlhAuX/lASVUWQhSGt45JH6mvEvXE2SfuEJd9z36X/X9eAIDmgdlSp8kyMiKGvEJ7XdITlFhaz65We+cGR2N8cDrpIGKfpCcL+s80kGFoSGORoXRwRm7if1T36GSAMKYJbim2Dmjej3lzJRo9UFdAaLIIB0xFmtZW7dwOgYcIEk+ciYXQPT2jLKHpqcOMW2vf2QMGYDYur38i9G3iW3t9etaQM+e5wkbkIc/sWU7cQ5t4bhodytDRJN8I7DcO5/Fc8IK1nJboLMm4TIvwjlwlRX4nraveV3iCMVcIg9QeGunc53BOaLr4M3PYKmvnr2qbhlDBkFRxkel2YqqFl/pEK5yun33SHiQgrstp0Rfo+J8wAfBW/XqGLzfQUgNPVla56GCDjlvMnPaobss+srRz5R0fLr5ANR0+bhTBabg1LXuh3hGmhjU4St1vfczZMOWIPma7C1dUL1T1TUxz5R4GvxEW11N68Qdis9LXsehlZ2/2aMNVWv5RXjIub6minMp0/98Zh7KArkNFSi6p/FPjKqTc3MAVhQeNrfucJw9ryuYn+Qth7O/Z1iZgqbhgQNvbjPRbWCjxx2ys8l0typSwOsjW9bnE6/RuL2mjxjwJf6fSJvLQuqcyBIp/uPegvhClf9+QVwAwPSUwBTCxTuXf4GBxZnPnhydNltC0Ocr15rh5mv9Geg0y8T+Ty+WsdZs7X4h/FvlK87cJLhLUPn0Jrqmu37LjjiWdEy3wvJgJKkxCmUay2ctUok670O63pc/sv9OYBlr8tHGSZfXtr+dMKp/5R4CvFPz3y3v6w0WnL6IWPnvh22oq34IMUq4DP+0aOfzLppbQ163MKv9Gy5mgewmxnz725catgQxtd1Ziw+FVHPe9r01HXuqRqJ4CMWiZIepfgG+W/d8YsfBmT4frNeY0wuMWnkubPXrUOAGUdyDlRalNqe7DHcI7bs4+kb9wSvuiVZiPCxZ1Dh3WOhr1iEux1cJBb/DBGmNkg8/Y+fUT9m77IdmoSVm/e1j1quqd/yORNQfRJHzDl7UxEDmxM8FV59+guAdXp0bjSah7IfPNbIzjH1Iz1G3btLyk9g5GFYcCbvfVQ3spPshDK3P30qNrEFssM6OZK9a1/hcVNQkdTEF2xyu3GRX1d8r9Nl4npa/xu3OrUPhQ8ChktPnMCIwcFyhCcpot1O5hJDrIZKzMkYbVckCYjess7XgITBTlcdBJB3qD4ZOVso6EjGQ0FxVbXK8MdJ8RwkMW/vloSduPKkMQUWtORAyIJc7MsW/+RX4dNkjBTS9sxUXSnU6dJsXJMJGE6ZN2WXYKqbODzEQjOGF5ZB3LkiEnCjCynIp0MS14I1JTFjIZDRoTMSF6c+SFdVYMlE/x5hyRMikvbaJFgDpuzQA6XJMwjhO3OzVf9y4UbVv4FIMVAiusBxyoAAAAASUVORK5CYII=" | tee /dev/tty


    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '21.7.1'

    - name: Running IRCTC Cypress Script
      uses: cypress-io/github-action@v6
      # continue-on-error: true
      with:
        browser: chrome
        command: npx cypress run --record --key 967b25a7-e4dd-4b5b-a143-d799131b2d3b --browser chrome --env USERNAME=${{secrets.USERNAME}},PASSWORD=${{secrets.PASSWORD}}


